export default [
  {
    _id: "elonMusk1tweet",
    retweet: false,
    likeComment: false,
    topic: "Elon Space",
    avatar: "elon_avatar.jpg",
    userName: "Elon Musk",
    handle: "@elonmusky",
    time: "2h",
    title:
      "Tesla Cybertruck lands on Mars and picks up the Curiosity rover on its 6' bed",
    image: "",
    postTitle:
      "Countdown: Inspirational4 Mission to Space | Netflix Official Site",
    liked: true,
    replied: false,
    replies: 123,
    retuits: 432,
    likes: 2345,
    tuit: "We might need a different name, as this is basically just Starlink with roaming capability, so you can take your terminal anywhere",
  },
  {
    _id: "234",
    retweet: true,
    likeComment: true,
    topic: "Traffic",
    avatar: "the_boring_company.jpg",
    userName: "The Boring Company",
    handle: "@boringcompany",
    time: "2h",
    title: "The Boring Company fixing traffic",
    image: "the_boring_company.jpg",
    postTitle:
      "Countdown: Inspirational4 Mission to Space | Netflix Official Site",
    liked: true,
    replied: false,
    likes: 2345,
    replies: 321,
    retuits: 432,
    tuit: "The Boring Company (TBC) is an American infrastructure and tunnel construction services company founded by Elon Musk. Its ongoing and proposed projects are designed for intra-city ('loop') transit systems.",
  },
  {
    _id: "345",
    retweet: false,
    likeComment: true,
    topic: "Brain Injuries",
    avatar: "neurolink.jpg",
    userName: "Neurolink",
    handle: "@neurolink",
    time: "3h",
    title: "Neurolink fixes paralisis and blindness",
    image: "neurolink_freshly_baked.jpg",
    postTitle:
      "Countdown: Inspirational4 Mission to Space | Netflix Official Site",
    liked: true,
    replied: false,
    likes: 3456,
    replies: 345,
    retuits: 654,
    tuit: "Neurolink is an American company founded by Elon Musk that specializes in brain to computer integration. The first application will be to cure spinal cord injuries so that paraplegics can walk again. Other applications include curing blindness and mental disorders.",
  },
];
